// Generated by Selenium IDE
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;

[TestFixture, Order(5)]
public class AdminTest {
  private FirefoxOptions _options;
  private IWebDriver _driver;


  [SetUp]
  public void SetUp() {
    _options = new FirefoxOptions { AcceptInsecureCertificates = true };
    _driver = new FirefoxDriver(_options);
  }


  [TearDown]
  protected void TearDown() {
    _driver.Quit();
  }


  [Test, Order(1)]
  public void adminAddGame() {
    _driver.Navigate().GoToUrl("https://localhost:7132/");
    _driver.Manage().Window.Size = new System.Drawing.Size(1612, 991);
    _driver.FindElement(By.Id("login")).Click();
    _driver.FindElement(By.Id("Input_UserName")).Click();
    _driver.FindElement(By.Id("Input_UserName")).SendKeys("admin");
    _driver.FindElement(By.Id("Input_Password")).Click();
    _driver.FindElement(By.Id("Input_Password")).SendKeys("Test1$");
    _driver.FindElement(By.Id("login-submit")).Click();
    _driver.FindElement(By.LinkText("Games")).Click();
    _driver.FindElement(By.LinkText("Add New Game")).Click();
    _driver.FindElement(By.Id("Title")).Click();
    _driver.FindElement(By.Id("Title")).SendKeys("Unit Test");
    _driver.FindElement(By.Id("Description")).Click();
    _driver.FindElement(By.Id("Description")).SendKeys("Interesting way to see if games are able to have fields populated");
    _driver.FindElement(By.Id("Price")).Click();
    _driver.FindElement(By.Id("Price")).SendKeys("25.00");
    _driver.FindElement(By.Id("GenreID")).Click();
    {
      var dropdown = _driver.FindElement(By.Id("GenreID"));
      dropdown.FindElement(By.XPath("//option[. = 'Puzzle']")).Click();
    }
    _driver.FindElement(By.CssSelector("option:nth-child(8)")).Click();
    _driver.FindElement(By.Id("Publisher")).Click();
    _driver.FindElement(By.Id("Publisher")).SendKeys("NPC Productions");
    _driver.FindElement(By.Id("ReleaseYear")).Click();
    _driver.FindElement(By.Id("ReleaseYear")).SendKeys("2023");
    _driver.FindElement(By.CssSelector(".btn-primary")).Click();
    Assert.That(_driver.FindElement(By.CssSelector(".text-white:last-child > td:nth-child(1)")).Text, Is.EqualTo("Unit Test"));
    _driver.FindElement(By.CssSelector(".text-white:last-child a:nth-child(2)")).Click();
    _driver.FindElement(By.CssSelector(".btn-danger")).Click();
    _driver.Close();
  }


    [Test, Order(2)]
    public void adminAddEvent()
    {
        _driver.Navigate().GoToUrl("https://localhost:7132/");
        _driver.Manage().Window.Size = new System.Drawing.Size(1612, 991);
        _driver.FindElement(By.Id("login")).Click();
        _driver.FindElement(By.Id("Input_UserName")).Click();
        _driver.FindElement(By.Id("Input_UserName")).SendKeys("admin");
        _driver.FindElement(By.Id("Input_Password")).Click();
        _driver.FindElement(By.Id("Input_Password")).SendKeys("Test1$");
        _driver.FindElement(By.Id("login-submit")).Click();
        _driver.FindElement(By.LinkText("Events")).Click();
        _driver.FindElement(By.LinkText("Add new Events")).Click();
        _driver.FindElement(By.Id("Name")).Click();
        _driver.FindElement(By.Id("Name")).SendKeys("Drawing Test Event");
        _driver.FindElement(By.Id("Location")).Click();
        _driver.FindElement(By.Id("Location")).SendKeys("Online");
        _driver.FindElement(By.Id("Description")).Click();
        _driver.FindElement(By.Id("Description")).SendKeys("Draw pictures of you favourite characters from whatever game");
        _driver.FindElement(By.Id("Date")).Click();
        _driver.FindElement(By.Id("Date")).SendKeys("002024-11-05T00:00");
        _driver.FindElement(By.CssSelector(".btn-primary")).Click();
        Assert.That(_driver.FindElement(By.CssSelector("tr:last-child > td:nth-child(1)")).Text, Is.EqualTo("Drawing Test Event"));
        _driver.FindElement(By.CssSelector("tr:last-child a:nth-child(2)")).Click();
        _driver.FindElement(By.CssSelector(".btn-danger")).Click();
    }
}
