// Generated by Selenium IDE
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;


[TestFixture, Order(2)]
public class LoginTest
{
    private FirefoxOptions _options;
    private IWebDriver _driver;


    [SetUp]
    public void SetUp()
    {
        _options = new FirefoxOptions { AcceptInsecureCertificates = true };
        _driver = new FirefoxDriver(_options);
    }


    [TearDown]
    protected void TearDown()
    {
        _driver.Quit();
    }


    [Test, Order(1)]
    public void memberLogsInSuccessfully()
    {
        _driver.Navigate().GoToUrl("https://localhost:7132/");
        _driver.Manage().Window.Size = new System.Drawing.Size(1212, 691);
        _driver.FindElement(By.Id("login")).Click();
        _driver.FindElement(By.Id("Input_UserName")).Click();
        _driver.FindElement(By.Id("Input_UserName")).SendKeys("TestMember");
        _driver.FindElement(By.Id("Input_Password")).Click();
        _driver.FindElement(By.Id("Input_Password")).SendKeys("Test1$");
        _driver.FindElement(By.Id("login-submit")).Click();
        _driver.FindElement(By.CssSelector(".display-4")).Click();
        Assert.That(_driver.FindElement(By.CssSelector(".display-4")).Text, Is.EqualTo("Welcome, this is Member page"));
    }


    [Test, Order(2)]
    public void memberIsLockedOutDueToUnsuccessfullLogin()
    {
        _driver.Navigate().GoToUrl("https://localhost:7132/");
        _driver.Manage().Window.Size = new System.Drawing.Size(1212, 691);
        _driver.FindElement(By.Id("login")).Click();
        _driver.FindElement(By.Id("Input_UserName")).Click();
        _driver.FindElement(By.Id("Input_UserName")).SendKeys("TestMember");
        _driver.FindElement(By.Id("Input_Password")).Click();
        _driver.FindElement(By.Id("Input_Password")).SendKeys("Test1S");
        _driver.FindElement(By.Id("login-submit")).Click();
        _driver.FindElement(By.Id("Input_Password")).Click();
        _driver.FindElement(By.Id("Input_Password")).SendKeys("Test2$");
        _driver.FindElement(By.Id("login-submit")).Click();
        _driver.FindElement(By.Id("Input_Password")).Click();
        _driver.FindElement(By.Id("Input_Password")).SendKeys("Test3$");
        _driver.FindElement(By.Id("login-submit")).Click();
        Assert.That(_driver.FindElement(By.CssSelector(".text-danger")).Text, Is.EqualTo("This account has been locked out, please try again later in 15 Minutes."));
        // Reduced lockout time for test user to 2 seconds
        Thread.Sleep(2000);
    }
}