// Generated by Selenium IDE
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;


[TestFixture, Order(3)]
public class PreferencesTest {
  private FirefoxOptions _options;
  private IWebDriver _driver;
  

  [SetUp]
  public void SetUp() {
        _options = new FirefoxOptions { AcceptInsecureCertificates = true };
        _driver = new FirefoxDriver(_options);
  }


  [TearDown]
  protected void TearDown() {
    _driver.Quit();
  }


  [Test, Order(1)]
  public void memberAddInitialPreferences() {
    _driver.Navigate().GoToUrl("https://localhost:7132/");
    _driver.Manage().Window.Size = new System.Drawing.Size(1212, 719);
    _driver.FindElement(By.Id("login")).Click();
    _driver.FindElement(By.Id("Input_UserName")).Click();
    _driver.FindElement(By.Id("Input_UserName")).SendKeys("TestMember");
    _driver.FindElement(By.Id("Input_Password")).Click();
    _driver.FindElement(By.Id("Input_Password")).SendKeys("Test1$");
    _driver.FindElement(By.Id("login-submit")).Click();
    _driver.FindElement(By.Id("manage")).Click();
    _driver.FindElement(By.Id("change-preferences")).Click();
    {
      var elements = _driver.FindElements(By.CssSelector(".form-group:nth-child(2) .item-container:nth-child(1)"));
      Assert.True(elements.Count == 0);
    }
    {
      var elements = _driver.FindElements(By.CssSelector(".form-group:nth-child(2) .item-container"));
      Assert.True(elements.Count == 0);
    }
    {
      string value = _driver.FindElement(By.Id("Input_LanguagesID")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("0"));
    }
    _driver.FindElement(By.CssSelector(".form-group:nth-child(1) svg")).Click();
    _driver.FindElement(By.CssSelector(".form-group:nth-child(1) li:nth-child(1)")).Click();
    _driver.FindElement(By.CssSelector(".form-group:nth-child(1) .btn-container svg")).Click();
    _driver.FindElement(By.CssSelector(".form-group:nth-child(1) li:nth-child(1)")).Click();
    _driver.FindElement(By.CssSelector(".form-group:nth-child(2) .btn-container")).Click();
    _driver.FindElement(By.CssSelector(".form-group:nth-child(2) svg")).Click();
    _driver.FindElement(By.CssSelector(".form-group:nth-child(2) li:nth-child(1)")).Click();
    _driver.FindElement(By.Id("Input_LanguagesID")).Click();
    {
      var dropdown = _driver.FindElement(By.Id("Input_LanguagesID"));
      dropdown.FindElement(By.XPath("//option[. = 'Japanese']")).Click();
    }
    _driver.FindElement(By.CssSelector("#Input_LanguagesID > option:nth-child(9)")).Click();
    _driver.FindElement(By.Id("update-preferences-button")).Click();
    _driver.FindElement(By.CssSelector(".alert")).Click();
    Assert.That(_driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Your preferences have been updated"));
  }


  [Test, Order(2)]
  public void memberEditInitialPreferences() {
    _driver.Navigate().GoToUrl("https://localhost:7132/");
    _driver.Manage().Window.Size = new System.Drawing.Size(1612, 1019);
    _driver.FindElement(By.Id("login")).Click();
    _driver.FindElement(By.Id("Input_UserName")).Click();
    _driver.FindElement(By.Id("Input_UserName")).SendKeys("TestMember");
    _driver.FindElement(By.Id("Input_Password")).Click();
    _driver.FindElement(By.Id("Input_Password")).SendKeys("Test1$");
    _driver.FindElement(By.Id("login-submit")).Click();
    _driver.FindElement(By.Id("manage")).Click();
    _driver.FindElement(By.Id("change-preferences")).Click();
    _driver.FindElement(By.CssSelector(".form-group:nth-child(1) .item-container:nth-child(1) line:nth-child(2)")).Click();
    _driver.FindElement(By.CssSelector(".form-group:nth-child(1) .btn-container")).Click();
    _driver.FindElement(By.CssSelector(".form-group:nth-child(1) .btn-container svg")).Click();
    _driver.FindElement(By.CssSelector(".form-group:nth-child(1) li:nth-child(4)")).Click();
    _driver.FindElement(By.CssSelector(".form-group:nth-child(2) .btn-container")).Click();
    _driver.FindElement(By.CssSelector(".form-group:nth-child(2) .btn-container svg")).Click();
    _driver.FindElement(By.CssSelector("li:nth-child(8)")).Click();
    _driver.FindElement(By.Id("Input_LanguagesID")).Click();
    {
      var dropdown = _driver.FindElement(By.Id("Input_LanguagesID"));
      dropdown.FindElement(By.XPath("//option[. = 'French']")).Click();
    }
    _driver.FindElement(By.CssSelector("#Input_LanguagesID > option:nth-child(2)")).Click();
    _driver.FindElement(By.Id("update-preferences-button")).Click();
    Assert.That(_driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Your preferences have been updated"));
  }
}
