// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chromium;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;


[TestFixture]
public class PreferencesTest {
  private FirefoxOptions options;
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  

  [SetUp]
  public void SetUp() {
        options = new FirefoxOptions();
        options.AcceptInsecureCertificates = true;
        driver = new FirefoxDriver(options);
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test, Order(1)]
  public void memberAddInitialPreferences() {
    driver.Navigate().GoToUrl("https://localhost:7132/");
    driver.Manage().Window.Size = new System.Drawing.Size(1212, 719);
    driver.FindElement(By.Id("login")).Click();
    driver.FindElement(By.Id("Input_UserName")).Click();
    driver.FindElement(By.Id("Input_UserName")).SendKeys("member");
    driver.FindElement(By.Id("Input_Password")).Click();
    driver.FindElement(By.Id("Input_Password")).SendKeys("Test1$");
    driver.FindElement(By.Id("login-submit")).Click();
    driver.FindElement(By.Id("manage")).Click();
    driver.FindElement(By.Id("change-preferences")).Click();
    {
      var elements = driver.FindElements(By.CssSelector(".form-group:nth-child(2) .item-container:nth-child(1)"));
      Assert.True(elements.Count == 0);
    }
    {
      var elements = driver.FindElements(By.CssSelector(".form-group:nth-child(2) .item-container"));
      Assert.True(elements.Count == 0);
    }
    {
      string value = driver.FindElement(By.Id("Input_LanguagesID")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("0"));
    }
    driver.FindElement(By.CssSelector(".form-group:nth-child(1) svg")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(1) li:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(1) .btn-container svg")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(1) li:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(2) .btn-container")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(2) svg")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(2) li:nth-child(1)")).Click();
    driver.FindElement(By.Id("Input_LanguagesID")).Click();
    {
      var dropdown = driver.FindElement(By.Id("Input_LanguagesID"));
      dropdown.FindElement(By.XPath("//option[. = 'Japanese']")).Click();
    }
    driver.FindElement(By.CssSelector("#Input_LanguagesID > option:nth-child(9)")).Click();
    driver.FindElement(By.Id("update-preferences-button")).Click();
    driver.FindElement(By.CssSelector(".alert")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Your preferences have been updated"));
  }
  [Test, Order(2)]
  public void memberEditInitialPreferences() {
    driver.Navigate().GoToUrl("https://localhost:7132/");
    driver.Manage().Window.Size = new System.Drawing.Size(1612, 1019);
    driver.FindElement(By.Id("login")).Click();
    driver.FindElement(By.Id("Input_UserName")).Click();
    driver.FindElement(By.Id("Input_UserName")).SendKeys("member");
    driver.FindElement(By.Id("Input_Password")).Click();
    driver.FindElement(By.Id("Input_Password")).SendKeys("Test1$");
    driver.FindElement(By.Id("login-submit")).Click();
    driver.FindElement(By.Id("manage")).Click();
    driver.FindElement(By.Id("change-preferences")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(1) .item-container:nth-child(1) line:nth-child(2)")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(1) .btn-container")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(1) .btn-container svg")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(1) li:nth-child(4)")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(2) .btn-container")).Click();
    driver.FindElement(By.CssSelector(".form-group:nth-child(2) .btn-container svg")).Click();
    driver.FindElement(By.CssSelector("li:nth-child(8)")).Click();
    driver.FindElement(By.Id("Input_LanguagesID")).Click();
    {
      var dropdown = driver.FindElement(By.Id("Input_LanguagesID"));
      dropdown.FindElement(By.XPath("//option[. = 'French']")).Click();
    }
    driver.FindElement(By.CssSelector("#Input_LanguagesID > option:nth-child(2)")).Click();
    driver.FindElement(By.Id("update-preferences-button")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Your preferences have been updated"));
  }
}
