// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ProfilesTest {
  private FirefoxOptions options;
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    options = new FirefoxOptions();
    options.AcceptInsecureCertificates = true;
    driver = new FirefoxDriver(options);
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test, Order(1)]
  public void memberEntersProfileInformationWithFutureBirthDate() {
    driver.Navigate().GoToUrl("https://localhost:7132/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
    driver.FindElement(By.Id("login")).Click();
    driver.FindElement(By.Id("Input_UserName")).Click();
    driver.FindElement(By.Id("Input_UserName")).SendKeys("member");
    driver.FindElement(By.Id("Input_Password")).Click();
    driver.FindElement(By.Id("Input_Password")).SendKeys("Test1$");
    driver.FindElement(By.Id("login-submit")).Click();
    driver.FindElement(By.Id("manage")).Click();
    driver.FindElement(By.Id("Profile_FirstName")).Click();
    driver.FindElement(By.Id("Profile_FirstName")).SendKeys("John");
    driver.FindElement(By.Id("Profile_LastName")).Click();
    driver.FindElement(By.Id("Profile_LastName")).SendKeys("Smith");
    driver.FindElement(By.Id("Profile_Gender")).Click();
    {
      var dropdown = driver.FindElement(By.Id("Profile_Gender"));
      dropdown.FindElement(By.XPath("//option[. = 'Male']")).Click();
    }
    driver.FindElement(By.CssSelector("option:nth-child(2)")).Click();
    driver.FindElement(By.Id("Profile_DOB")).Click();
    driver.FindElement(By.Id("Profile_DOB")).SendKeys("2023-11-30");
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.CssSelector(".col")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".text-danger")).Text, Is.EqualTo("Birth date must be a valid date that\'s in the past."));
  }
  [Test, Order(2)]
  public void memberEntersProfileDetails() {
    driver.Navigate().GoToUrl("https://localhost:7132/");
    driver.Manage().Window.Size = new System.Drawing.Size(1612, 991);
    driver.FindElement(By.Id("login")).Click();
    driver.FindElement(By.Id("Input_UserName")).Click();
    driver.FindElement(By.Id("Input_UserName")).SendKeys("member");
    driver.FindElement(By.Id("Input_Password")).Click();
    driver.FindElement(By.Id("Input_Password")).SendKeys("Test1$");
    driver.FindElement(By.Id("login-submit")).Click();
    driver.FindElement(By.Id("manage")).Click();
    driver.FindElement(By.Id("Profile_FirstName")).Click();
    driver.FindElement(By.Id("Profile_FirstName")).SendKeys("John");
    driver.FindElement(By.Id("Profile_LastName")).Click();
    driver.FindElement(By.Id("Profile_LastName")).SendKeys("Smith");
    driver.FindElement(By.Id("Profile_Gender")).Click();
    {
      var dropdown = driver.FindElement(By.Id("Profile_Gender"));
      dropdown.FindElement(By.XPath("//option[. = 'Male']")).Click();
    }
    driver.FindElement(By.CssSelector("option:nth-child(2)")).Click();
    driver.FindElement(By.Id("Profile_DOB")).Click();
    driver.FindElement(By.Id("Profile_DOB")).SendKeys("1982-09-22");
    driver.FindElement(By.Id("Profile_RecievePromotions")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.CssSelector(".alert")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Your profile has been updated"));
  }
}
