// Generated by Selenium IDE
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;


[TestFixture, Order(6)]
public class ReportsTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private readonly string path = Path.GetTempPath();


  [SetUp]
  public void SetUp() {
    var options = new ChromeOptions();
    Directory.CreateDirectory(path);
    options.AddUserProfilePreference("download.default_directory", path);
    options.AddUserProfilePreference("download.prompt_for_download", false);
    options.AddUserProfilePreference("disable-popup-blocking", "true");
    driver = new ChromeDriver(options);
    vars = new Dictionary<string, object>();
  }


  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  public string waitForWindow(int timeout) {
    try {
      Thread.Sleep(timeout);
    } catch(Exception e) {
      Console.WriteLine("{0} Exception caught.", e);
    }
    var whNow = ((IReadOnlyCollection<object>)driver.WindowHandles).ToList();
    var whThen = ((IReadOnlyCollection<object>)vars["WindowHandles"]).ToList();
    if (whNow.Count > whThen.Count) {
      return whNow.Except(whThen).First().ToString();
    } else {
      return whNow.First().ToString();
    }
  }


  [Test, Order(1)]
  public void adminViewReport()
  {
    driver.Navigate().GoToUrl("https://localhost:7132/");
    driver.Manage().Window.Size = new System.Drawing.Size(1050, 708);
    driver.FindElement(By.Id("login")).Click();
    driver.FindElement(By.Id("Input_UserName")).Click();
    driver.FindElement(By.Id("Input_UserName")).SendKeys("admin");
    driver.FindElement(By.Id("Input_Password")).Click();
    driver.FindElement(By.Id("Input_Password")).SendKeys("Test1$");
    driver.FindElement(By.Id("login-submit")).Click();
    driver.FindElement(By.LinkText("Report")).Click();
    vars["WindowHandles"] = driver.WindowHandles;
    driver.FindElement(By.LinkText("View")).Click();
    vars["win1464"] = waitForWindow(2000);
    driver.SwitchTo().Window(vars["win1464"].ToString());
    var elements = driver.FindElements(By.CssSelector("embed"));
    Assert.True(elements.Count > 0);
  }


  [Test, Order(2)]
  public void adminDownloadReport() {
    var filesToDelete = Directory.GetFiles(path, "CVGS_*.pdf", SearchOption.TopDirectoryOnly);
    if(filesToDelete != null)
    {
        foreach(var fileToDelete in filesToDelete)
        {
            File.Delete(fileToDelete);
        }
    }
    driver.Navigate().GoToUrl("https://localhost:7132/");
    driver.Manage().Window.Size = new System.Drawing.Size(1050, 708);
    driver.FindElement(By.Id("login")).Click();
    driver.FindElement(By.Id("Input_UserName")).Click();
    driver.FindElement(By.Id("Input_UserName")).SendKeys("admin");
    driver.FindElement(By.Id("Input_Password")).Click();
    driver.FindElement(By.Id("Input_Password")).SendKeys("Test1$");
    driver.FindElement(By.Id("login-submit")).Click();
    driver.FindElement(By.LinkText("Report")).Click();
    driver.FindElement(By.LinkText("Download")).Click();
    Thread.Sleep(5000);
    var file = Directory.GetFiles(path, "CVGS_*.pdf", SearchOption.TopDirectoryOnly);
    Assert.That(file != null);
    File.Delete(file[0]) ;
  }
}
