// Generated by Selenium IDE
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;


[TestFixture, Order(1)]
public class SignupTest {
  private FirefoxOptions _options;
  private IWebDriver _driver;
  

  [SetUp]
  public void SetUp() {
    _options = new FirefoxOptions { AcceptInsecureCertificates = true };
    _driver = new FirefoxDriver(_options);
  }


  [TearDown]
  protected void TearDown() {
    _driver.Quit();
  }


  [Test, Order(1)]
  public void userFailsToProvideAValidPasswordOnSignUp() {
    _driver.Navigate().GoToUrl("https://localhost:7132/");
    _driver.Manage().Window.Size = new System.Drawing.Size(1212, 691);
    _driver.FindElement(By.Id("register")).Click();
    _driver.FindElement(By.Id("Input_UserName")).Click();
    _driver.FindElement(By.Id("Input_UserName")).SendKeys("TestMember");
    _driver.FindElement(By.Id("Input_Email")).Click();
    _driver.FindElement(By.Id("Input_Email")).SendKeys("TestMember@sharklasers.com");
    _driver.FindElement(By.Id("Input_Password")).Click();
    _driver.FindElement(By.Id("Input_Password")).SendKeys("password");
    _driver.FindElement(By.Id("Input_ConfirmPassword")).Click();
    _driver.FindElement(By.Id("Input_ConfirmPassword")).SendKeys("password");
    _driver.FindElement(By.Id("registerSubmit")).Click();
    Assert.That(_driver.FindElement(By.CssSelector(".text-danger li:nth-child(1)")).Text, Is.EqualTo("Passwords must have at least one non alphanumeric character."));
    Assert.That(_driver.FindElement(By.CssSelector(".text-danger li:nth-child(2)")).Text, Is.EqualTo("Passwords must have at least one digit (\'0\'-\'9\')."));
    Assert.That(_driver.FindElement(By.CssSelector("li:nth-child(3)")).Text, Is.EqualTo("Passwords must have at least one uppercase (\'A\'-\'Z\')."));
  }


  [Test, Order(2)]
  public void userSignsUpSuccessfully() {
    _driver.Navigate().GoToUrl("https://localhost:7132/");
    _driver.Manage().Window.Size = new System.Drawing.Size(1612, 991);
    _driver.FindElement(By.Id("register")).Click();
    _driver.FindElement(By.Id("Input_UserName")).Click();
    _driver.FindElement(By.Id("Input_UserName")).SendKeys("TestMember");
    _driver.FindElement(By.Id("Input_Email")).Click();
    _driver.FindElement(By.Id("Input_Email")).SendKeys("TestMember@sharklasers.com");
    _driver.FindElement(By.Id("Input_Password")).Click();
    _driver.FindElement(By.Id("Input_Password")).SendKeys("Test1$");
    _driver.FindElement(By.Id("Input_ConfirmPassword")).Click();
    _driver.FindElement(By.Id("Input_ConfirmPassword")).SendKeys("Test1$");
    _driver.FindElement(By.Id("registerSubmit")).Click();
    Assert.That(_driver.FindElement(By.CssSelector("p")).Text, Is.EqualTo("Please check your email to confirm your account."));
    }
}
