# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET build and test

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and Run Selenium tests
      run:
        dotnet build --no-restore --project D:\a\OnlineGameStore\OnlineGameStore\EventService\EventService.csproj --project D:\a\OnlineGameStore\OnlineGameStore\GameStore\GameService.csproj --project D:\a\OnlineGameStore\OnlineGameStore\PROG3050-HMJJ\PROG3050-HMJJ.csproj 
        dotnet test /testcontainer:firefox --start
